<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>json</string>
  </array>
  <key>name</key>
  <string>JSON</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>:</string>
      <key>end</key>
      <string>(?=,|\{|\}|\[)</string>
      <key>name</key>
      <string>entry</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>:</string>
          <key>name</key>
          <string>invalid.illegal</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#quoted</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(true|false|null)\b</string>
          <key>name</key>
          <string>keyword.reserved</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#invalid</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>match</key>
      <string>(?&lt;!\[)".+?"\s*(?=:)</string>
      <key>name</key>
      <string>entity.name.tag</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#quoted</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#numeric</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#invalid</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>escape</key>
    <dict>
      <key>match</key>
      <string>\\.</string>
      <key>name</key>
      <string>keyword.escape</string>
    </dict>
    <key>quoted</key>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.double</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#escape</string>
        </dict>
      </array>
    </dict>
    <key>invalid</key>
    <dict>
      <key>match</key>
      <string>[A-Za-z_']+</string>
      <key>name</key>
      <string>invalid.illegal</string>
    </dict>
    <key>numeric</key>
    <dict>
      <key>match</key>
      <string>-?\d+(\.\d+)?([eE](\+|-)?)?(\.\d+)?</string>
      <key>name</key>
      <string>constant.numeric</string>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.json</string>
  <key>uuid</key>
  <string>2FE0BC28-1CA6-446E-BC91-774C786C63D5</string>
</dict>
</plist>
